name: Semantic Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
     
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
     
      - name: Install Dependencies
        run: npm ci  # use npm ci for a clean, reproducible build

      - name: Build App
        run: npm run build
     
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
